<div class="portal-top"><div class="brand"><?php if($m->getPlatformBrandAssetPath('compact')):?><img src="?brand_asset=compact" alt="<?=h($brand['product_name'])?>"><?php elseif($m->getPlatformBrandAssetPath('icon')):?><img src="?brand_asset=icon" alt="<?=h($brand['product_name'])?>"><?php else:?><div class="brand-text"><strong><?=h($brand['product_name'])?></strong><span><?=h($brand['edition'])?></span></div><?php endif;?></div><div class="portal-user"><?php if($u):?><?=h($u['user_name'])?><a href="?logout=1">Sign out</a><?php endif;?></div></div>
<div class="wrap"><?php if($error):?><div class="alert bad"><?=h($error)?></div><?php endif;?><?php if($notice):?><div class="alert good"><?=h($notice)?></div><?php endif;?>
<?php if(!$u):?><div class="card login-card"><div class="login-brand"><?php if($m->getPlatformBrandAssetPath('logo')):?><img src="?brand_asset=logo" alt="<?=h($brand['product_name'])?>"><?php else:?><h1><?=h($brand['product_name'])?></h1><?php endif;?></div><h2>Fax Sign In</h2><p class="sub"><?=h($brand['edition'])?></p><form method="post"><input type="hidden" name="action" value="login"><label>Username</label><input name="username" required autocomplete="username" autofocus><label>Password</label><input type="password" name="password" required autocomplete="current-password"><div style="margin-top:16px"><button class="btn" style="width:100%">Sign In</button></div></form></div>
<?php else:?><div class="page-head"><div><h1>Fax Platform</h1><p>Send and manage your fax communications.</p></div></div><div class="tabs"><a class="<?=$view==='faxes'?'active':''?>" href="<?=$portalSelf?>">Faxes</a><a class="<?=$view==='settings'?'active':''?>" href="<?=$portalSelf?>?view=settings">Settings</a></div>
<?php if($view==='faxes'):?><div class="grid"><div class="card"><h2>My Fax Account</h2><p><strong><?=h($u['user_name'])?></strong></p><p><?=h($u['email'])?></p><p class="small">Default identity: <?=h($u['default_identity_name']?:'Not assigned')?></p></div>
<?php if(!empty($u['can_send'])):?><div class="card"><h2>Send Fax</h2><?php if(empty($u['default_identity_id'])):?><div class="alert bad">An administrator must assign a default fax identity before you can send.</div><?php else:?><form method="post" enctype="multipart/form-data" id="sendfax"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><label>Fax Number</label><input name="fax_number" required><label>Cover Page</label><select name="coverpage_id" id="coverpage_id"><option value="0">No cover page</option><?php foreach($covers as $c):?><option value="<?=(int)$c['id']?>"><?=h($c['name'].(!empty($c['owner_user_id'])?' (My Cover Page)':''))?></option><?php endforeach;?></select><label>Document <span class="small">(optional when sending a cover page)</span></label><input type="file" name="document" id="document" accept="application/pdf,image/tiff,image/png,image/jpeg"><label>Recipient Name</label><input name="recipient_name"><label>Recipient Company</label><input name="recipient_company"><label>Subject</label><input name="subject"><label>Notes / Cover Message</label><textarea name="notes" rows="4"></textarea><div class="form-actions"><button class="btn gray" type="submit" name="action" value="preview" formtarget="_blank">Preview</button><button class="btn" type="submit" name="action" value="send">Send Fax</button></div><p class="small">Preview opens the prepared fax immediately in a new tab and does not queue or retain a draft. You may also send a cover page by itself without an attachment.</p></form><script>document.getElementById('sendfax').addEventListener('submit',function(e){if(!document.getElementById('document').files.length&&document.getElementById('coverpage_id').value==='0'){e.preventDefault();alert('Attach a document or select a cover page.');}});</script><?php endif;?></div><?php endif;?></div>
<div class="card"><h2>My Faxes</h2><div class="tablewrap"><table><thead><tr><th>ID</th><th>Date</th><th>Direction</th><th>From</th><th>To</th><th>Pages</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php if(!$jobs):?><tr><td colspan="8">No fax records yet.</td></tr><?php endif;?><?php foreach($jobs as $j):?><tr><td>#<?=(int)$j['id']?></td><td><?=h($m->formatTimestamp($j['created_at']))?></td><td><?=h(ucfirst($j['direction']))?></td><td><?=h($j['source_number'])?></td><td><?=h($j['destination_number'])?></td><td><?=(int)$j['pages']?></td><td class="status"><?=h(strtoupper($j['status']))?><div class="small"><?=h($j['status_text'])?></div></td><td><div class="actions"><?php if(!empty($j['pdf_path'])):?><a class="btn gray" target="_blank" href="?file=preview&id=<?=(int)$j['id']?>">Preview</a><a class="btn gray" href="?file=download&id=<?=(int)$j['id']?>">PDF</a><?php endif;?><?php if($j['status']==='draft'&&!empty($u['can_send'])):?><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="send_draft"><input type="hidden" name="id" value="<?=(int)$j['id']?>"><button class="btn">Send Fax</button></form><?php endif;?><?php if(!empty($u['can_delete'])):?><form method="post" onsubmit="return confirm('Delete this fax record and stored file?');"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$j['id']?>"><button class="btn red">Delete</button></form><?php endif;?></div></td></tr><?php endforeach;?></tbody></table></div></div>
<?php else:?><div class="settings-grid"><div><div class="card"><h2>My Sender Profile</h2><p class="small">These details are yours, not the system-wide company profile. They are used on your cover pages, which is useful when several companies share one PBX system.</p><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="save_preferences"><div class="profile-grid"><div><label>Your Name</label><input name="full_name" value="<?=h($u['full_name']??'')?>"></div><div><label>Company Name</label><input name="company_name" value="<?=h($u['company_name']??'')?>"></div><div><label>Email Address</label><input type="email" name="email" value="<?=h($u['email'])?>"></div><div><label>Phone Number</label><input name="phone_number" value="<?=h($u['phone_number']??'')?>"></div><div><label>Fax Number / Outbound Caller ID</label><input name="fax_number" value="<?=h($u['fax_number']??'')?>" placeholder="Defaults to assigned fax identity"><div class="small">Normal outbound faxes and Test Fax request this number as caller ID.</div></div><div><label>Website</label><input name="website" value="<?=h($u['website']??'')?>"></div><div class="wide"><label>Address</label><input name="address1" value="<?=h($u['address1']??'')?>"></div><div class="wide"><label>Address Line 2</label><input name="address2" value="<?=h($u['address2']??'')?>"></div><div><label>City</label><input name="city" value="<?=h($u['city']??'')?>"></div><div><label>State</label><input name="state" value="<?=h($u['state']??'')?>"></div><div><label>ZIP / Postal Code</label><input name="postal_code" value="<?=h($u['postal_code']??'')?>"></div></div><div class="small" style="margin-top:12px"><strong>Assigned inbound DID(s):</strong> <?=!empty($inboundDids)?h(implode(', ',$inboundDids)):'None'?><?php
$normalizeDid = static function ($number) {
    return preg_replace('/\D+/', '', (string)$number);
};
$normalizedInboundDids = array_values(array_filter(array_map($normalizeDid, $inboundDids), static function ($v) { return $v !== ''; }));
$userFaxDid = $normalizeDid($u['fax_number'] ?? '');
$faxDidAssigned = ($userFaxDid !== '' && in_array($userFaxDid, $normalizedInboundDids, true));
?><?php if(!empty($u['fax_number'])&&!empty($inboundDids)&&!$faxDidAssigned):?><div class="alert bad" style="margin-top:10px">Your outbound fax number <?=h($u['fax_number'])?> does not match a DID assigned to your managed fax destination. Return faxes to that number require the carrier and inbound call routing to deliver that DID to Fax Platform.</div><?php endif;?></div><hr style="border:0;border-top:1px solid var(--ia-border);margin:18px 0"><h3 style="margin:0 0 8px">Email Notifications</h3><label class="check"><input type="checkbox" name="notify_inbound" <?=!empty($u['notify_inbound'])?'checked':''?>> Email me inbound faxes</label><label class="check"><input type="checkbox" name="notify_success" <?=!empty($u['notify_success'])?'checked':''?>> Email me when an outbound fax succeeds</label><label class="check"><input type="checkbox" name="notify_failure" <?=!empty($u['notify_failure'])?'checked':''?>> Email me when an outbound fax fails</label><div style="margin-top:12px"><button class="btn">Save Settings</button></div></form></div><div class="card"><h2>Change Password</h2><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="change_password"><label>Current Password</label><input type="password" name="current_password" required autocomplete="current-password"><label>New Password</label><input type="password" name="new_password" required minlength="8" autocomplete="new-password"><label>Confirm New Password</label><input type="password" name="confirm_password" required minlength="8" autocomplete="new-password"><div style="margin-top:12px"><button class="btn">Change Password</button></div></form></div><div class="card"><h2>Test Fax</h2><p class="small">Sends a one-page test fax using your sender profile and assigned fax identity to <strong>18884732963</strong> (HP Fax Test). HP normally returns a fax to the caller ID presented by your outbound fax, making this useful for verifying both sending and inbound DID routing.</p><form method="post" onsubmit="return confirm('Send a test fax to 18884732963 now?');"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="test_fax"><button class="btn">Send Test Fax</button></form><p class="small" style="margin-top:10px">The fax module will request your configured user fax number as outbound caller ID. A trunk explicitly configured to force its own CID can still override it.</p></div></div>
<div><div class="card"><h2><?= $editCover?'Edit My Cover Page':'Create My Cover Page' ?></h2><p class="small">Choose a visual layout, then customize the text. Available variables: {{from_name}}, {{from_company}}, {{from_phone}}, {{from_fax}}, {{from_email}}, {{from_address}}, {{from_website}}, {{to_name}}, {{to_company}}, {{to_number}}, {{subject}}, {{date}}, {{message}}.</p><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="id" value="<?=$editCover?(int)$editCover['id']:0?>"><label>Name</label><input name="name" required value="<?=h($editCover['name']??'')?>"><label>Layout</label><select name="template_style"><option value="professional" <?=($editCover['template_style']??'professional')==='professional'?'selected':''?>>Professional</option><option value="classic" <?=($editCover['template_style']??'')==='classic'?'selected':''?>>Classic Business</option><option value="minimal" <?=($editCover['template_style']??'')==='minimal'?'selected':''?>>Clean & Simple</option></select><label>Template Text</label><textarea name="template_html" rows="15" required><?=h($editCover['template_html']??"TO: {{to_name}}
COMPANY: {{to_company}}
FAX: {{to_number}}

FROM: {{from_name}}
COMPANY: {{from_company}}
PHONE: {{from_phone}}
FAX: {{from_fax}}
EMAIL: {{from_email}}
ADDRESS: {{from_address}}

SUBJECT: {{subject}}
DATE: {{date}}

MESSAGE:
{{message}}")?></textarea><div style="margin-top:12px" class="actions"><button class="btn gray" type="submit" name="action" value="preview_cover" formtarget="_blank">Preview</button><button class="btn" type="submit" name="action" value="save_cover">Save Cover Page</button><?php if($editCover):?> <a class="btn gray" href="?view=settings">Cancel</a><?php endif;?></div></form></div><div class="card"><h2>Built-in Templates</h2><p class="small">Copy any built-in template to your account, then edit the copy without changing anyone else's template.</p><div class="tablewrap"><table style="min-width:0"><thead><tr><th>Template</th><th>Layout</th><th>Action</th></tr></thead><tbody><?php foreach($globalCovers as $c):?><tr><td><?=h($c['name'])?></td><td><?=h(ucwords(str_replace('_',' ',$c['template_style']??'professional')))?></td><td><div class="actions"><a class="btn gray" target="_blank" href="?cover_preview=<?=(int)$c['id']?>">Preview</a><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="copy_cover"><input type="hidden" name="id" value="<?=(int)$c['id']?>"><button class="btn gray">Copy & Edit</button></form></div></td></tr><?php endforeach;?></tbody></table></div></div><div class="card"><h2>My Cover Pages</h2><?php if(!$myCovers):?><p class="small">You have not created any personal cover pages yet.</p><?php else:?><div class="tablewrap"><table style="min-width:0"><thead><tr><th>Name</th><th>Layout</th><th>Actions</th></tr></thead><tbody><?php foreach($myCovers as $c):?><tr><td><?=h($c['name'])?></td><td><?=h(ucwords(str_replace('_',' ',$c['template_style']??'professional')))?></td><td><div class="actions"><a class="btn gray" target="_blank" href="?cover_preview=<?=(int)$c['id']?>">Preview</a><a class="btn gray" href="?view=settings&edit_cover=<?=(int)$c['id']?>">Edit</a><form method="post" onsubmit="return confirm('Delete this cover page?');"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete_cover"><input type="hidden" name="id" value="<?=(int)$c['id']?>"><button class="btn red">Delete</button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></div></div></div><?php endif;?><?php endif;?></div>
<div class="portal-footer"><strong><?=h($brand['product_name'])?></strong><?php if(!empty($brand['company_name'])):?> · <?=h($brand['company_name'])?><?php endif;?></div></body></html>
