<div class="row"><div class="col-md-5"><div class="tffax-panel"><h2>Add Inbound Fax Mailbox</h2><form method="post" action="config.php?display=tffax&view=destinations"><input type="hidden" name="tffax_action" value="save_destination">
<div class="form-group"><label>Name</label><input class="form-control" name="name" required placeholder="Front Desk Fax"></div>
<div class="form-group"><label>Fax Identity</label><select class="form-control" name="identity_id"><option value="">System default</option><?php foreach($identities as $i):?><option value="<?=$i['id']?>"><?=htmlspecialchars($i['name'])?></option><?php endforeach;?></select></div>
<div class="form-group"><label>Assigned Users</label><?php if($users):?><select class="form-control" name="user_ids[]" multiple size="<?=min(8,max(3,count($users)))?>"><?php foreach($users as $u):?><option value="<?=$u['id']?>"><?=htmlspecialchars($u['user_name'])?></option><?php endforeach;?></select><p class="help-block">These assignments are owned by Fax Platform only. Use Ctrl/Command to select multiple users.</p><?php else:?><p class="text-muted">Create users on the <strong>Fax Users</strong> tab first if this mailbox should belong to one or more users.</p><?php endif;?></div>
<div class="form-group"><label>Email To</label><input class="form-control" name="email_to" placeholder="frontdesk@example.com"></div><div class="form-group"><label>Attachment Format</label><select class="form-control" name="attach_format"><option value="pdf">PDF</option><option value="tiff">TIFF</option></select></div><div class="checkbox"><label><input type="checkbox" name="keep_copy" checked> Keep local copy</label></div><div class="checkbox"><label><input type="checkbox" name="enabled" checked> Enabled</label></div><button class="btn btn-primary">Save Mailbox</button></form></div></div>
<div class="col-md-7"><div class="tffax-panel"><h2>Inbound Fax Mailboxes</h2><p class="text-muted">Each enabled mailbox becomes its own selectable inbound-call destination. The Automatic DID/CID Router is also registered separately.</p><table class="table table-striped"><thead><tr><th>Name</th><th>Identity</th><th>Assigned Users</th><th>Email</th><th>Status</th><th></th></tr></thead><tbody><?php if(!$destinations):?><tr><td colspan="6" class="text-muted">No inbound fax mailboxes configured.</td></tr><?php endif;?><?php foreach($destinations as $d):?><tr><td><?=htmlspecialchars($d['name'])?></td><td><?=htmlspecialchars($d['identity_name']?:'System default')?></td><td><?=htmlspecialchars($d['assigned_users']?:'—')?></td><td><?=htmlspecialchars($d['email_to'])?></td><td><?=$d['enabled']?'Enabled':'Disabled'?></td><td><form method="post" action="config.php?display=tffax&view=destinations" onsubmit="return confirm('Delete this inbound fax mailbox? Routing rules pointing to it will also be removed.');"><input type="hidden" name="tffax_action" value="delete_destination"><input type="hidden" name="id" value="<?=$d['id']?>"><button class="btn btn-xs btn-danger">Delete</button></form></td></tr>
<?php if($users):?><tr><td colspan="6"><form class="form-inline" method="post" action="config.php?display=tffax&view=destinations"><input type="hidden" name="tffax_action" value="set_destination_users"><input type="hidden" name="id" value="<?=$d['id']?>"><label class="small">Update users:&nbsp;</label><select class="form-control input-sm" name="user_ids[]" multiple size="2" style="min-width:220px"><?php $sel=array_filter(array_map('intval',explode(',',(string)$d['assigned_user_ids']))); foreach($users as $u):?><option value="<?=$u['id']?>" <?=in_array((int)$u['id'],$sel,true)?'selected':''?>><?=htmlspecialchars($u['user_name'])?></option><?php endforeach;?></select> <button class="btn btn-xs btn-default">Save Users</button></form></td></tr><?php endif;?>
<?php endforeach;?></tbody></table></div></div></div>
<div class="tffax-panel"><h2>How to Route Inbound Fax Calls</h2><p><strong>Dedicated mailbox:</strong> In Inbound Routes, select <em>Fax Platform → [mailbox name]</em>. <strong>Automatic:</strong> select <em>Fax Platform → Automatic DID/CID Router</em> and configure rules on the Routing tab. In both modes Fax Platform stores the original DID and Caller ID with the fax record.</p></div>
