<div class="table-responsive"><table class="table table-striped tffax-table"><thead><tr><th>ID</th><th>Time</th><th>Owner</th><th>Direction</th><th>From</th><th>To</th><th>Identity / Destination</th><th>Fax Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<?php if(!$jobs): ?><tr><td colspan="10" class="text-muted">No fax records yet.</td></tr><?php endif; ?>
<?php foreach($jobs as $j): ?><tr>
<td>#<?= (int)$j['id']?></td><td><?=htmlspecialchars($module->formatTimestamp($j['created_at']))?></td><td><?=htmlspecialchars($j['user_name']?:'—')?></td>
<td><span class="tffax-dir <?=htmlspecialchars($j['direction'])?>"><?=htmlspecialchars(ucfirst($j['direction']))?></span></td><td><?=htmlspecialchars($j['source_number'])?></td><td><?=htmlspecialchars($j['destination_number'])?></td><td><?=htmlspecialchars($j['identity_name']?:$j['destination_name']?:'—')?></td>
<td><?php if((int)$j['pages']>0 || $j['bitrate'] || $j['transport'] || $j['remote_station_id']): ?><strong><?= (int)$j['pages']?> page<?=((int)$j['pages']===1?'':'s')?></strong><?php if($j['bitrate']): ?><div class="small text-muted"><?=htmlspecialchars($j['bitrate'])?> bps</div><?php endif; ?><?php if($j['transport']): ?><div class="small text-muted">Policy: <?=htmlspecialchars(ucfirst($j['transport']))?></div><?php endif; ?><?php if($j['remote_station_id']): ?><div class="small text-muted">Remote: <?=htmlspecialchars($j['remote_station_id'])?></div><?php endif; ?><?php elseif($j['status']==='draft'): ?><span class="text-muted">Draft PDF ready</span><?php else: ?>—<?php endif; ?><?php if(!empty($j['coverpage_name'])):?><div class="small text-muted">Cover: <?=htmlspecialchars($j['coverpage_name'])?></div><?php endif;?></td>
<td><span class="tffax-status status-<?=htmlspecialchars($j['status'])?>"><?=htmlspecialchars(strtoupper($j['status']))?></span><?php if($j['status_text']): ?><div class="small text-muted"><?=htmlspecialchars($j['status_text'])?></div><?php endif; ?></td>
<td class="tffax-actions">
  <?php if(!empty($j['pdf_path'])): ?><a class="btn btn-xs btn-info" target="_blank" href="config.php?display=tffax&quietmode=1&tffax_file=preview&id=<?=(int)$j['id']?>"><i class="fa fa-eye"></i> Preview</a> <a class="btn btn-xs btn-default" href="config.php?display=tffax&quietmode=1&tffax_file=download&id=<?=(int)$j['id']?>"><i class="fa fa-download"></i> PDF</a><?php endif; ?>
  <?php if($j['status']==='draft'): ?><form method="post" action="config.php?display=tffax&view=<?=htmlspecialchars($view)?>" class="tffax-inline"><input type="hidden" name="tffax_action" value="send_draft"><input type="hidden" name="id" value="<?=(int)$j['id']?>"><button class="btn btn-xs btn-success"><i class="fa fa-paper-plane"></i> Send</button></form><?php endif; ?>
  <?php if($j['direction']==='inbound' && empty($j['destination_id']) && !empty($destinations)): ?><form method="post" action="config.php?display=tffax&view=<?=htmlspecialchars($view)?>" class="form-inline tffax-inline"><input type="hidden" name="tffax_action" value="assign_job_destination"><input type="hidden" name="id" value="<?= (int)$j['id'] ?>"><select class="form-control input-sm" name="destination_id" required><option value="">Assign...</option><?php foreach($destinations as $d): if(!$d['enabled'])continue; ?><option value="<?=$d['id']?>"><?=htmlspecialchars($d['name'])?></option><?php endforeach;?></select><button class="btn btn-xs btn-default">Move</button></form><?php endif; ?>
  <form method="post" action="config.php?display=tffax&view=<?=htmlspecialchars($view)?>" class="tffax-inline" onsubmit="return confirm('Delete fax job #<?= (int)$j['id'] ?> and its stored document files? This cannot be undone.');"><input type="hidden" name="tffax_action" value="delete_job"><input type="hidden" name="view" value="<?=htmlspecialchars($view)?>"><input type="hidden" name="id" value="<?= (int)$j['id'] ?>"><button type="submit" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i> Delete</button></form>
</td></tr><?php endforeach; ?></tbody></table></div>
<?php $tffaxHasActiveJobs=false;foreach($jobs as $tffaxJob){if(in_array(strtolower((string)$tffaxJob['status']),['queued','dialing','sending'],true)){$tffaxHasActiveJobs=true;break;}}if($tffaxHasActiveJobs):?><script>(function(){var delay=4000;function r(){if(document.hidden){setTimeout(r,delay);return;}var a=document.activeElement;if(a&&/^(INPUT|SELECT|TEXTAREA|BUTTON)$/.test(a.tagName)){setTimeout(r,delay);return;}window.location.reload();}setTimeout(r,delay);})();</script><?php endif;?>
