<div class="tffax-panel tffax-form-panel"><h2>Fax Engine Settings</h2><form method="post" action="config.php?display=tffax&view=<?=$view?>"><input type="hidden" name="tffax_action" value="save_settings"><input type="hidden" name="view" value="settings">
<div class="row"><div class="col-md-6 form-group"><label>Spool Directory</label><input class="form-control" name="spool_dir" value="<?=htmlspecialchars($settings['spool_dir']??'/var/spool/asterisk/tffax')?>"></div><div class="col-md-6 form-group"><label>Outbound Dial Context</label><input class="form-control" name="outbound_context" value="<?=htmlspecialchars($settings['outbound_context']??'from-internal')?>"><p class="help-block">Normally <code>from-internal</code> so Fax Platform follows the PBX's existing outbound routes and access-code rules.</p></div></div>
<div class="row"><div class="col-md-6 form-group"><label>Default Local Station ID (TSID)</label><input class="form-control" name="local_station_id" value="<?=htmlspecialchars($settings['local_station_id']??'')?>"><p class="help-block">Fax station identifier. This is separate from the SIP/PSTN outbound Caller ID enforced by trunk configuration.</p></div><div class="col-md-6 form-group"><label>Default Header</label><input class="form-control" name="header_text" value="<?=htmlspecialchars($settings['header_text']??'')?>"></div></div>
<?php $rates=[2400,4800,7200,9600,12000,14400]; ?>
<div class="row"><div class="col-md-3 form-group"><label>ECM</label><select class="form-control" name="ecm"><option value="yes" <?=($settings['ecm']??'yes')==='yes'?'selected':''?>>Enabled</option><option value="no" <?=($settings['ecm']??'')==='no'?'selected':''?>>Disabled</option></select></div><div class="col-md-3 form-group"><label>Minimum Rate</label><select class="form-control" name="min_rate"><?php foreach($rates as $r):?><option value="<?=$r?>" <?=((string)($settings['min_rate']??'4800')===(string)$r)?'selected':''?>><?=number_format($r)?> bps</option><?php endforeach;?></select></div><div class="col-md-3 form-group"><label>Maximum Rate</label><select class="form-control" name="max_rate"><?php foreach($rates as $r):?><option value="<?=$r?>" <?=((string)($settings['max_rate']??'14400')===(string)$r)?'selected':''?>><?=number_format($r)?> bps</option><?php endforeach;?></select></div><div class="col-md-3 form-group"><label>Max Attempts</label><input type="number" min="1" max="10" class="form-control" name="max_attempts" value="<?=htmlspecialchars($settings['max_attempts']??'3')?>"></div></div>
<div class="row"><div class="col-md-12 form-group"><label>Email From Address</label><input type="email" class="form-control" name="email_from" value="<?=htmlspecialchars($settings['email_from']??'')?>" placeholder="fax@example.com"><p class="help-block">Used for inbound fax delivery and outbound success/failure notifications. Leave blank to use fax@PBX-hostname through the server's local mail transport.</p></div></div>
<div class="row"><div class="col-md-6 form-group"><label>Interface Theme</label><select class="form-control" name="ui_theme"><option value="refined" <?=($settings['ui_theme']??'refined')==='refined'?'selected':''?>>Refined</option><option value="classic" <?=($settings['ui_theme']??'')==='classic'?'selected':''?>>Classic</option></select><p class="help-block">Applies to both the Fax administration pages and the standalone <code>/fax/</code> user portal. Refined adds a richer header, enhanced cards, navigation and visual hierarchy. Classic keeps the simpler presentation.</p></div><div class="col-md-6 form-group"><label>Display Timezone</label><input class="form-control" name="timezone" value="<?=htmlspecialchars($settings['timezone']??'America/Chicago')?>" placeholder="America/Chicago"><p class="help-block">IANA timezone used for portal/admin timestamps, notification times, and cover-page dates. Database timestamps remain UTC. Example: <code>America/Chicago</code>.</p></div></div>
<div class="row"><div class="col-md-6 form-group"><label>T.38 Policy</label><select class="form-control" name="t38_mode"><?php foreach(['auto'=>'Auto (allow audio fallback)','prefer'=>'Prefer T.38 (actively request, allow fallback)','audio'=>'Audio only (G.711)','t38'=>'T.38 only'] as $k=>$v):?><option value="<?=$k?>" <?=($settings['t38_mode']??'auto')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select><p class="help-block">The selected policy controls SendFAX behavior. The SIP trunk/endpoint must also permit T.38 for T.38 negotiation to succeed.</p></div><div class="col-md-6 form-group"><label>Retention Days</label><input type="number" min="0" max="3650" class="form-control" name="retain_days" value="<?=htmlspecialchars($settings['retain_days']??'365')?>"><p class="help-block">0 means retain indefinitely. Automatic purge is reserved for a later maintenance worker.</p></div></div>
<div class="tffax-panel" style="margin-top:20px"><h2>Email Templates</h2>
<p class="help-block">These templates are PBX-wide and are managed by administrators only. User notification checkboxes still determine whether a user receives inbound, success, or failure messages.</p>
<div class="alert alert-info"><strong>Available variables:</strong> <code>{{job_id}}</code>, <code>{{from_number}}</code>, <code>{{to_number}}</code>, <code>{{recipient_name}}</code>, <code>{{recipient_company}}</code>, <code>{{subject}}</code>, <code>{{status}}</code>, <code>{{status_code}}</code>, <code>{{status_text}}</code>, <code>{{pages}}</code>, <code>{{remote_station_id}}</code>, <code>{{local_station_id}}</code>, <code>{{destination_name}}</code>, <code>{{user_name}}</code>, <code>{{date}}</code>. Inbound also provides <code>{{sender}}</code> and <code>{{received_at}}</code>; outbound success/failure also provide <code>{{result}}</code> and <code>{{completed_at}}</code>.</div>
<div class="row"><div class="col-md-12 form-group"><h3>Inbound Fax Received</h3><label>Subject</label><input class="form-control" name="email_tpl_inbound_subject" value="<?=htmlspecialchars($settings['email_tpl_inbound_subject']??'Inbound fax from {{sender}}')?>"><label style="margin-top:10px">Message</label><textarea class="form-control" name="email_tpl_inbound_body" rows="8"><?=htmlspecialchars($settings['email_tpl_inbound_body']??"A new inbound fax was received.\n\nFrom: {{from_number}}\nTo DID: {{to_number}}\nMailbox: {{destination_name}}\nPages: {{pages}}\nRemote station: {{remote_station_id}}\nReceived: {{received_at}}\n")?></textarea></div></div>
<div class="row"><div class="col-md-6 form-group"><h3>Outbound Fax Success</h3><label>Subject</label><input class="form-control" name="email_tpl_success_subject" value="<?=htmlspecialchars($settings['email_tpl_success_subject']??'Fax sent successfully to {{to_number}}')?>"><label style="margin-top:10px">Message</label><textarea class="form-control" name="email_tpl_success_body" rows="9"><?=htmlspecialchars($settings['email_tpl_success_body']??"Your fax was transmitted successfully.\n\nTo: {{to_number}}\nStatus: {{status_text}}\nPages: {{pages}}\nRemote station: {{remote_station_id}}\nCompleted: {{completed_at}}\nJob: #{{job_id}}\n")?></textarea></div>
<div class="col-md-6 form-group"><h3>Outbound Fax Failure</h3><label>Subject</label><input class="form-control" name="email_tpl_failure_subject" value="<?=htmlspecialchars($settings['email_tpl_failure_subject']??'Fax failed to {{to_number}}')?>"><label style="margin-top:10px">Message</label><textarea class="form-control" name="email_tpl_failure_body" rows="9"><?=htmlspecialchars($settings['email_tpl_failure_body']??"Your fax transmission failed.\n\nTo: {{to_number}}\nStatus: {{status_text}}\nPages: {{pages}}\nRemote station: {{remote_station_id}}\nCompleted: {{completed_at}}\nJob: #{{job_id}}\n")?></textarea></div></div>
<p class="help-block">Templates are plain-text email bodies so they remain compatible with the PBX's local mail transport and a wide range of mail clients.</p></div>
<div class="alert alert-info"><strong>Recommended general-purpose profile:</strong> ECM enabled, minimum 4,800 bps, maximum 14,400 bps, T.38 Auto. Fax History records the <em>actual negotiated</em> rate reported by Asterisk and the configured transport policy used for the attempt.</div>
<button class="btn btn-primary">Save Settings</button></form></div>
